# Generated by Django 4.1.1 on 2022-09-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(),
        ),
    ]
